env: "local" # dev, prod
token_ttl: 1h

grpc:
  port: 44044
  timeout: 5s

postgres:
  host: "postgres"
  port: 5432
  user: "restaurant"
  password: "password"
  dbname: "restaurant_pg"
  sslmode: "disable"