env: "local"
app_secret: "app secret" 

http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s

clients:
  sso:
    address: auth_service:44044
    timeout: 5s
    retries_count: 5

postgres:
  host: "postgres"
  port: 5432
  user: "restaurant"
  password: "password"
  dbname: "restaurant_pg"
  sslmode: "disable"

redis:
  host: "redis:6379"
  password: "password"
  db: 0

rabbitmq:
  url: "amqp://restaurant:password@rabbitmq:5672/"
  queue_name: "notifications_queue"
